ARG UBUNTU_DIST=noble
FROM ubuntu:noble

ARG UBUNTU_DIST
ARG headscale_VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG HEADSCALE_RELEASE

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/lib/systemd/system
RUN mkdir -p /output/etc/headscale
RUN mkdir -p /output/usr/share/doc/headscale
RUN mkdir -p /output/DEBIAN

COPY ${HEADSCALE_RELEASE}/headscale /output/usr/bin/headscale
COPY output/headscale.service /output/usr/lib/systemd/system/headscale.service
COPY output/config.yaml /output/etc/headscale/config.yaml
COPY output/DEBIAN/control /output/DEBIAN/control
COPY output/DEBIAN/postinst /output/DEBIAN/postinst
COPY output/DEBIAN/prerm /output/DEBIAN/prerm
COPY output/copyright /output/usr/share/doc/headscale/copyright
COPY output/changelog.Debian /output/usr/share/doc/headscale/changelog.Debian
COPY output/README.md /output/usr/share/doc/headscale/README.md

RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/usr/share/doc/headscale/changelog.Debian
RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/headscale/changelog.Debian
RUN sed -i "s/headscale_VERSION/$headscale_VERSION/g" /output/usr/share/doc/headscale/changelog.Debian
RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/DEBIAN/control
RUN sed -i "s/headscale_VERSION/$headscale_VERSION/" /output/DEBIAN/control
RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control

RUN chmod 755 /output/usr/bin/headscale
RUN chmod 755 /output/DEBIAN/postinst
RUN chmod 755 /output/DEBIAN/prerm

RUN dpkg-deb --build /output /headscale_${FULL_VERSION}.deb
