ARG UBUNTU_DIST=noble
FROM ubuntu:noble

ARG UBUNTU_DIST
ARG headscale_VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG HEADSCALE_RELEASE

# TODO: implement headscale build.
# This Dockerfile mirrors uv-debian's structure but is not wired up to any
# real build logic yet: build_debian.sh currently exits before invoking
# `docker build`, and the output/ packaging skeleton below has not been
# created for headscale. Fill in output/DEBIAN/control, output/copyright,
# output/changelog.Debian and output/README.md, then point COPY at the
# downloaded headscale release, before using this file.

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/share/doc/headscale
RUN mkdir -p /output/DEBIAN

# COPY ${HEADSCALE_RELEASE}/* /output/usr/bin/
# COPY output/DEBIAN/control /output/DEBIAN/
# COPY output/copyright /output/usr/share/doc/headscale/
# COPY output/changelog.Debian /output/usr/share/doc/headscale/
# COPY output/README.md /output/usr/share/doc/headscale/

# RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/usr/share/doc/headscale/changelog.Debian
# RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/headscale/changelog.Debian
# RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/DEBIAN/control
# RUN sed -i "s/headscale_VERSION/$headscale_VERSION/" /output/DEBIAN/control
# RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
# RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control

# RUN dpkg-deb --build /output /headscale_${FULL_VERSION}.deb
